config/routes.rb
Rails.application.routes.draw do
  resources :products, except: :index
  devise_for :users
  root "static_pages#show", page: "home"
  get "/static_pages/*page", to: "static_pages#show"
  get "/manage_product", to: "static_pages#manage_product"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/feedback.rb
class Feedback < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :notifier, class_name: User.name, foreign_key: "notifier_id"
  belongs_to :notifiee, class_name: User.name, foreign_key: "notifiee_id"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_details
  has_many :products, through: :order_details
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :order_details
  has_many :orders, through: :order_details
  has_many :wish_lists, dependent: :destroy
  has_many :feedbacks, dependent: :destroy

  has_attached_file :item
  validates_attachment_content_type :item,
    content_type: "application/zip"

  has_attached_file :image_product, styles: {medium: "300x300>",
    thumb: "100x100>"}, default_url: "default.png"
  validates_attachment_content_type :image_product,
    content_type: /\Aimage\/.*\z/
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  has_one :profile, dependent: :destroy
  has_many :wish_lists, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :notifications_as_notifier, class_name: Notification.name,
    foreign_key: "notifier_id"
  has_many :notifications_as_notifiee, class_name: Notification.name,
    foreign_key: "notifiee_id"
end

app/models/wish_list.rb
class WishList < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  helper_method :user_product
  before_action :find_product, except: [:index, :create, :new]
  before_action :categories, only: [:new, :edit]
  before_action :authenticate_user!, except: [:show]

  def index
    @products = Product.all
  end

  def new
    @product = current_user.products.build
  end

  def create
    @product = current_user.products.build product_params
    respond_to do |format|
      if @product.save
        format.html{redirect_to @product, notice: t(".success")}
        format.json{render :show, status: :created, location: @product}
      else
        format.html{render :new}
        format.json{render json: @product.errors, status: :unprocessable_entity}
      end
    end
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @product.update product_params
        format.html{redirect_to @product, notice: t(".success")}
        format.json{render :show, status: :ok, location: @product}
      else
        format.html{render :edit}
        format.json{render json: @product.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html{redirect_to products_url, notice: t(".success")}
      format.json{head :no_content}
    end
  end

  private
  def user_product
    current_user == @product.user
  end

  def find_product
    @product = Product.find_by id: params[:id]
    if @product.blank?
      redirect_to root_url, notice: t(".not_found")
    else
      @product
    end
  end

  def categories
    @categories = Category.all
  end

  def product_params
    params.require(:product).permit :category_id, :title, :summary, :content,
      :price, :image_product, :item
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def show
    if valid_page?
      @products = Product.all if params[:page] == "home"
      render "static_pages/#{params[:page]}"
    else
      render file: "public/404.html", status: :not_found
    end
  end

  def manage_product
    @products = current_user.products
  end

  private
  def valid_page?
    File.exist? Pathname.new(
      Rails.root.join("app", "views", "static_pages",
        "#{params[:page]}.html.erb")
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t(".home"), root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to t(".manage_products"), manage_product_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t ".account" %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t(".settings"), edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to t(".log_out"), destroy_user_session_path,
                  method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t(".signup"), new_user_registration_path %></li>
          <li><%= link_to t(".login"), new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
<% console %>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application",
  "data-turbolinks-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HappyDownload</title>
    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for product, html: {multipart: true} do |f| %>
  <% if product.errors.any? %>
    <div class="error-explanation">
      <h2><%= pluralize(product.errors.count, t(".error")) %> :</h2>
      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :title, t(".title") %>
  <%= f.text_field :title, class: "form-control" %>

  <%= f.label :summary, t(".summary") %>
  <%= f.text_field :summary, class: "form-control" %>

  <%= f.label :content, t(".content") %>
  <%= f.text_field :content, class: "form-control" %>

  <%= f.label :pricet, t(".price") %>
  <%= f.text_field :content, class: "form-control" %>

  <%= f.label :link_preview, t(".link_preview") %>
  <%= f.text_field :link_preview, class: "form-control" %>

  <%= f.label :image_product  %>
  <%= f.file_field :image_product, class: "form-control" %>

  <%= f.label :item  %>
  <%= f.file_field :item, class: "form-control" %>

  <%= f.label :category_id %>
  <%= f.collection_select(:category_id, @categories, :id, :name) %>

  <div class="actions">
    <%= f.submit t(".create") %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1><%= t ".title" %></h1>

<%= render "form", product: @product %>

<%= link_to t(".show"), @product %> |
<%= link_to t(".back"), products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1><%= t ".title" %></h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <table>
        <tr>
          <th><%= t ".name" %></th>
          <th><%= t ".action" %></th>
        </tr>
        <tr>
          <td><%= product.title %></td>
          <td><%= link_to t(".show"), product %></td>
          <td><%= link_to t(".edit"), edit_product_path(product) %></td>
          <td><%= link_to t(".destroy"), product, method: :delete,
            data: {confirm: t(".sure")} %></td>
        </tr>
      </table>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t(".new_product"), new_product_path %>

app/views/products/new.html.erb
<h1><%= t ".new_product" %></h1>

<%= render "form", product: @product, categories: @categories  %>

<%= link_to t(".back"), products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-6">
    <div class="thumbnail">
      <%= image_tag @product.image_product.url{:medium} %>
    </div>
  </div>
  <div class="col-md-6">
    <h3>
      <%= @product.title %>
    </h3>
    <p>
      <%= number_to_currency @product.price %>
    </p>
    <p>
      <%= @product.content %>
    </p>
    <% if user_product %>
      <p>
        <%= link_to t(".edit"), edit_product_path(@product) %>
      </p>
    <% else %>
      <%= link_to t(".buy_now"), new_product_path(@product) %>
    <% end %>
      <%= link_to t(".back"), root_path %>
  </div>
</div>

app/views/static_pages/about.html.erb
<h2><%= t ".title" %></h2>

<p><%= t ".content" %></p>

app/views/static_pages/home.html.erb
<h2><%= t ".title" %></h2>
<p class="center"><%= t ".content" %></p>
<p class="notice"><%= notice %></p>
<h1>
  <%= t ".all_products" %>
</h1>
<div class="center">
  <div class="row">
    <% @products.each do |product| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag(product.image_product.url(:thumb)), product %>
        <div class="caption">
          <h3><%= product.title %></h3>
          <p><%= number_to_currency product.price %></p>
          <p><%= t ".created_by " "#{product.user.name}" %></p>
        </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/static_pages/manage_product.html.erb
<p class="notice"><%= notice %></p>
<%= link_to t("new_product"), new_product_path %>
<table class="table table-striped table-bordered">
  <tr>
    <th><%= t ".image" %></th>
    <th><%= t ".name" %></th>
    <th><%= t ".content" %></th>
    <th><%= t ".price" %></th>
    <th><%= t ".action" %></th>
  </tr>
  <% @products.each do |product| %>
    <tr>
      <td><%= image_tag(product.image_product.url(:thumb)) %></td>
      <td><%= product.title %></td>
      <td><%= product.content %></td>
      <td><%= number_to_currency(product.price) %></td>
      <td>
        <%= link_to t(".show"), product %>
        <%= link_to t(".edit"), edit_product_path(product) %>
        <%= link_to t(".destroy"), product,
          method: :delete, data: {confirm: t(".sure")}, class: "btn btn-link" %>
      </td>
    </tr>
  <% end %>
</table>